//
// Created by kefas on 26.2.23.
//

#ifndef PICO_KIT_FRAMEWORK_CORE_HPP
#define PICO_KIT_FRAMEWORK_CORE_HPP

#include "tusb.h"
#include "tusb_data.hpp"
#include "Types.hpp"

#include "Timers.hpp"

#include <vector>

namespace rpgui::core
{
    class Cursor;
}

namespace rpgui::event
{
    class MouseDispatcher;
    class Handler;
}

namespace rpgui::page
{
    class Page;
}

namespace rpgui::type
{
    enum class MouseEventType;

}

using namespace rpgui::page;
using namespace rpgui::event;
using namespace rpgui::type;

namespace rpgui::core
{

    /// @brief Core class responsible for drawing, event handling, cursor adjusting and page selecting
    class MainApp
    {
    private:
        inline static std::vector<Page *> _pages;
        inline static Page *_selectedPage;

        static enum class clickState {
            none,
            pressed,
        } _clickState;

        static MouseDispatcher _mouseHandler;
        static Cursor _cursor;

    public:
        MainApp() = delete;
        MainApp(const MainApp&) = delete;
        ~MainApp() = delete;

        /// @brief Initializes VGA libraries.
        /// @warning May change base core clock speed! Init before other IO.
        static void Init();

        /// @brief Adds Page to core
        /// @param page - to be added 
        /// @return ID of added page
        static ID AddPage(Page *page);

        /// @brief Select page to be drawn on the display
        /// @param id ID of page to be selected
        static void SelectPage(ID id);

        /// @brief Select page to be drawn on the display
        /// @param at Index of page in list of stored pages
        static void SelectPageAt(uint8_t at);


        /// @brief Gets ID of currently drawn page
        /// @return ID of selected page
        static ID GetSelectedPageId();

        /// @brief Gets position of currently drawn page in list of pages
        /// @return Index of selected page
        static uint8_t GetSelectedPageAt();

        /// @brief Draws selected page, updates cursor pos, handles clicks
        /// @details Draws cursor then page. Handles data from mouse generated by user, fires and handles events associated with left mouse click
        static void Update();


        /// @brief Adds event listener to core
        /// @param type Type of mouse event to trigger listener
        /// @param handler Handler function and element reference
        /// @param priority Priority of processing event
        static void AddListener(MouseEventType type, const Handler &handler, const uint8_t priority = 0);

        /// @brief Used for testing
        static void ClearHandlers();

    private:
        static void drawPage();

        static void processMouseInput();

        static void processMouseMovement();

        static void updateOnCoreX();

        static void drawCursor();
    };

} // namespace rpgui::core

#endif // PICO_KIT_FRAMEWORK_CORE_HPP