name: Build framework

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ARM GCC toolchain
      run: sudo apt-get install -y gcc-arm-none-eabi

    - name: Configure CMake project
      run: |
        mkdir build
        cd build
        cmake ..
        
    - name: Build project
      run: |
        cd build
        make
        
